### ISSUE TITLE
Tutorials for how to add custom environment

### ISSUE THREAD

**Issue by huangshiyu13** [OpenRL-Lab/openrl#139]
### 📚 Documentation

Tutorials for how to add custom environment

### Checklist

- [X] I have checked that there is no similar [issues](https://github.com/OpenRL-Lab/openrl/issues) in the repo
- [X] I have read the [documentation](https://openrl-docs.readthedocs.io/)

**Comment by astonisingHSR** [comment]
Hi,

Firstly, I would like to express my appreciation for developing this excellent project. During my usage, I would like to customize the environment to meet my specific requirements. However, I couldn't find any guidance on how to customize the environment in the documentation.

I would appreciate it if you could provide detailed instructions on customizing the environment, including the steps involved and the available configuration options and their impacts. This would enable me to make the necessary adjustments based on my needs.

If possible, please provide a document or guide that covers the detailed steps for customizing the environment, the available configuration options, and their effects.

I believe such documentation would be highly beneficial not only for me but also for other users.

Thank you!

Best regards

**Comment by huangshiyu13** [comment]
Sure. We will provide such guidance in the future.

**Comment by huangshiyu13** [comment]
@astonisingHSR 
We have added the tutorial for adding a user-defined environment here: https://openrl-docs.readthedocs.io/en/latest/custom_env/index.html

- Code examples: https://github.com/OpenRL-Lab/openrl/tree/main/examples/custom_env

- 中文教程参考：https://openrl-docs.readthedocs.io/zh/latest/custom_env/index.html
