### ISSUE TITLE
[Feature Request] Feature request for saving best model，saving checkpoints，and custom stop condition

### ISSUE THREAD

**Issue by jiangzhangze** [OpenRL-Lab/openrl#25]
### 🚀 Feature

1.Saving best model during training；
2.Saving checkpoint and loading checkpoint；
3.Custom stop condition，such as: number of episodes，mean rewards......

### Motivation

1.The final model may not be the best model；
2.Supports of checkpoints can be easy for tuning hyperparameters；
3.ppo_agent seems only support total time steps as the stop condition right now.

### Additional context

1.[stable_baselines3.common.eval_callback](https://stable-baselines3.readthedocs.io/en/master/guide/callbacks.html#evalcallback),
2.[stable_baselines3.common.checkpoint_callback](https://stable-baselines3.readthedocs.io/en/master/guide/callbacks.html#checkpointcallback),
3.[rllib](https://docs.ray.io/en/master/rllib/user-guides.html)

### Checklist

- [X] I have checked that there is no similar [issues](https://github.com/OpenRL-Lab/openrl/issues) in the repo
- [X] I have read the [documentation](https://openrl-docs.readthedocs.io/)

**Comment by huangshiyu13** [comment]
can  save checkpoints now: #114 

Example: https://github.com/OpenRL-Lab/openrl/tree/main/examples/cartpole
