### ISSUE TITLE
[Feature Request] add SMAC envs

### ISSUE THREAD

**Issue by strivebfq** [OpenRL-Lab/openrl#37]
### 🚀 Feature

add SMAC envs
paper link：[The StarCraft Multi-Agent Challenge](https://arxiv.org/abs/1902.04043)

### Motivation

No response

### Additional context

No response

### Checklist

- [X] I have checked that there is no similar [issues](https://github.com/OpenRL-Lab/openrl/issues) in the repo
- [X] I have read the [documentation](https://openrl-docs.readthedocs.io/)

**Comment by huangshiyu13** [comment]
add in #109
