### ISSUE TITLE
[Bug]: 执行示例代码，报错  KeyError: 'reward'

### ISSUE THREAD

**Issue by FIWE2030** [OpenRL-Lab/openrl#48]
### 🐛 Bug

执行示例代码，报错了，好像是创建环境报错了

### To Reproduce

# train_ppo.py
from openrl.envs.common import make
from openrl.modules.common import PPONet as Net
from openrl.runners.common import PPOAgent as Agent

env = make("CartPole-v1", env_num=9) # 创建环境，并设置环境并行数为9
net = Net(env) # 创建神经网络
agent = Agent(net) # 初始化训练器
agent.train(total_time_steps=20000) # 开始训练，并设置环境运行总步数为20000

# 创建用于测试的环境，并设置环境并行数为9，设置渲染模式为group_human
env = make("CartPole-v1", env_num=9, render_mode="group_human")
agent.set_env(env) # 训练好的智能体设置需要交互的环境
obs, info = env.reset() # 环境进行初始化，得到初始的观测值和环境信息
while True:
    action, _ = agent.act(obs) # 智能体根据环境观测输入预测下一个动作
    # 环境根据动作执行一步，得到下一个观测值、奖励、是否结束、环境信息
    obs, r, done, info = env.step(action)
    if any(done): break
env.close() # 关闭测试环境

### Relevant log output / Error message

```shell
File "/Users/env/venv/lib/python3.8/site-packages/openrl/envs/vec_env/wrappers/reward_wrapper.py", line 46, in step
    rewards, new_infos = self.reward_class.step_reward(data=extra_data)
  File "/Users/env/venv/lib/python3.8/site-packages/openrl/rewards/base_reward.py", line 15, in step_reward
    rewards = data["reward"].copy()
KeyError: 'reward'
```

### System Info

MacOS  12.1 (21C52)
MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports) 
2.3 GHz 四核Intel Core i7
16 GB 3733 MHz LPDDR4X

### Checklist

- [X] I have checked that there is no similar [issues](https://github.com/OpenRL-Lab/openrl/issues) in the repo
- [X] I have read the [documentation](https://openrl-docs.readthedocs.io/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I have version numbers, operating system and environment, where applicable

**Comment by huangshiyu13** [comment]
bug fixed in #27

**Comment by FIWE2030** [comment]
我版本是  v0.0.6  还是有这个错

**Comment by huangshiyu13** [comment]
> 我版本是 v0.0.6 还是有这个错

v0.0.6是有这个bug。请使用v0.0.7或者最新的代码。

`pip install --upgrade openrl==v0.0.7`

**Comment by FIWE2030** [comment]
Could not find a version that satisfies the requirement openrl==v0.0.7 (from versions: 0.0.3, 0.0.4, 0.0.5, 0.0.6)
ERROR: No matching distribution found for openrl==v0.0.7

找不到这个版本

**Comment by huangshiyu13** [comment]
因为你使用了镜像源，可以通过：
`pip install -i https://pypi.org/simple/ --upgrade openrl`
来安装

**Comment by FIWE2030** [comment]
socket 超时了。。
![image](https://user-images.githubusercontent.com/21697518/236723345-f7566b54-a327-496e-ae76-86f7a8597111.png)

**Comment by FIWE2030** [comment]
![image](https://user-images.githubusercontent.com/21697518/236723447-502c8c76-3462-454f-a729-53bf10b024d3.png)

**Comment by FIWE2030** [comment]
是不是开了vpn就会好点，我没开vpn

**Comment by huangshiyu13** [comment]
你换成清华源头应该就可以了：
https://www.cnblogs.com/huangshiyu13/p/9338649.html
https://www.cnblogs.com/huangshiyu13/p/8453353.html

然后执行 pip install --upgrade openrl

**Comment by FIWE2030** [comment]
换成清华源了，但是升级后版本还是 v0.0.6

**Comment by huangshiyu13** [comment]
你可以通过源码安装：
git clone https://github.com/OpenRL-Lab/openrl.git && cd openrl
pip install -e .

**Comment by FIWE2030** [comment]
源码安装，可以了，回复速度很快，感谢
