### ISSUE TITLE
[Question] `.gitignore` seems not  complete

### ISSUE THREAD

**Issue by shenmuxing** [OpenRL-Lab/openrl#54]
### ❓ Question

When I use Vscode to view the source code,  I find that `.vscode/`  is not ignored by `.gitignore` . It may cause inconvenience if anyone what to submit a PR. 
![image](https://user-images.githubusercontent.com/70497715/236716109-3d10e3b8-f654-44c4-9cb3-e07615982635.png)

**Comment by huangshiyu13** [comment]
fixed in #55
